// This file was generated by `crates/core/src/bin/generate_types.rs`.

// Do not edit this file manually.

// If you are an AI, and you absolutely have to edit this file, please confirm with the user first.

export type Project = { id: string, name: string, dev_script: string | null, dev_script_working_dir: string | null, default_agent_working_dir: string | null, remote_project_id: string | null, board_id: string | null, created_at: Date, updated_at: Date, };

export type CreateProject = { name: string, repositories: Array<CreateProjectRepo>, };

export type UpdateProject = { name: string | null, dev_script: string | null, dev_script_working_dir: string | null, default_agent_working_dir: string | null, board_id: string | null, };

export type SearchResult = { path: string, is_file: boolean, match_type: SearchMatchType, };

export type SearchMatchType = "FileName" | "DirectoryName" | "FullPath";

export type Board = { id: string, name: string, description: string | null, is_template: boolean, template_group_id: string | null, template_name: string | null, template_description: string | null, template_icon: string | null, created_at: Date, updated_at: Date, };

export type CreateBoard = { name: string, description: string | null, };

export type UpdateBoard = { name: string | null, description: string | null, };

export type TemplateInfo = { id: string, template_group_id: string, name: string, description: string, icon: string, };

export type KanbanColumn = { id: string, board_id: string, name: string, slug: string, position: number, color: string | null, is_initial: boolean, is_terminal: boolean, 
/**
 * When true, entering this column creates a new attempt/workspace
 */
starts_workflow: boolean, status: TaskStatus, agent_id: string | null, 
/**
 * What the agent should produce before moving to the next column
 */
deliverable: string | null, 
/**
 * Variable name for structured deliverable (e.g., "decision")
 */
deliverable_variable: string | null, 
/**
 * JSON array of allowed values for the deliverable variable
 */
deliverable_options: string | null, is_template: boolean, template_group_id: string | null, created_at: Date, updated_at: Date, };

export type CreateKanbanColumn = { name: string, slug: string, position: number, color: string | null, is_initial: boolean | null, is_terminal: boolean | null, starts_workflow: boolean | null, status: TaskStatus | null, agent_id: string | null, deliverable: string | null, deliverable_variable: string | null, deliverable_options: string | null, };

export type UpdateKanbanColumn = { name: string | null, slug: string | null, position: number | null, color: string | null, is_initial: boolean | null, is_terminal: boolean | null, starts_workflow: boolean | null, status: TaskStatus | null, 
/**
 * Agent ID - uses double Option to distinguish between "not provided" (None) and "explicitly null" (Some(None))
 * - None: Keep existing value (field not in request)
 * - Some(None): Clear the agent (field is null in request)
 * - Some(Some(uuid)): Set to new agent
 */
agent_id?: string | null, deliverable: string | null, deliverable_variable: string | null, deliverable_options: string | null, };

export type StateTransition = { id: string, 
/**
 * Board ID for board-level transitions (NULL for project/task level)
 */
board_id: string | null, 
/**
 * Project ID for project-level transitions (NULL for board/task level)
 */
project_id: string | null, 
/**
 * Task ID for task-level transitions (NULL for board/project level)
 */
task_id: string | null, from_column_id: string, 
/**
 * Where to go when condition matches (success path)
 */
to_column_id: string, 
/**
 * Where to go when condition doesn't match (else path)
 */
else_column_id: string | null, 
/**
 * Where to go when max_failures is reached (escalation path)
 */
escalation_column_id: string | null, name: string | null, requires_confirmation: boolean, 
/**
 * JSON key to check in .vibe/decision.json (e.g., "decision")
 */
condition_key: string | null, 
/**
 * Value to match for this transition (e.g., "approve" or "reject")
 */
condition_value: string | null, 
/**
 * Number of times the else path can be taken before escalation
 */
max_failures: number | null, is_template: boolean, template_group_id: string | null, created_at: Date, };

export type StateTransitionWithColumns = { id: string, board_id: string | null, project_id: string | null, task_id: string | null, from_column_id: string, from_column_name: string, 
/**
 * Where to go when condition matches (success path)
 */
to_column_id: string, to_column_name: string, 
/**
 * Where to go when condition doesn't match (else path)
 */
else_column_id: string | null, else_column_name: string | null, 
/**
 * Where to go when max_failures is reached (escalation path)
 */
escalation_column_id: string | null, escalation_column_name: string | null, name: string | null, requires_confirmation: boolean, condition_key: string | null, condition_value: string | null, 
/**
 * Number of times the else path can be taken before escalation
 */
max_failures: number | null, 
/**
 * Computed scope for UI display
 */
scope: TransitionScope, created_at: Date, };

export type CreateStateTransition = { from_column_id: string, 
/**
 * Where to go when condition matches (success path)
 */
to_column_id: string, 
/**
 * Where to go when condition doesn't match (else path)
 */
else_column_id: string | null, 
/**
 * Where to go when max_failures is reached (escalation path)
 */
escalation_column_id: string | null, name: string | null, requires_confirmation: boolean | null, condition_key: string | null, condition_value: string | null, 
/**
 * Number of times the else path can be taken before escalation
 */
max_failures: number | null, };

export type UpdateStateTransition = { from_column_id: string | null, to_column_id: string | null, 
/**
 * Double Option: None = keep existing, Some(None) = set null, Some(Some(id)) = set value
 */
else_column_id?: string | null, escalation_column_id?: string | null, name: string | null, requires_confirmation: boolean | null, condition_key: string | null, condition_value: string | null, max_failures: number | null, };

export type TransitionScope = "board" | "project" | "task";

export type Repo = { id: string, path: string, name: string, display_name: string, created_at: Date, updated_at: Date, };

export type ProjectRepo = { id: string, project_id: string, repo_id: string, setup_script: string | null, cleanup_script: string | null, copy_files: string | null, parallel_setup_script: boolean, };

export type CreateProjectRepo = { display_name: string, git_repo_path: string, };

export type UpdateProjectRepo = { setup_script: string | null, cleanup_script: string | null, copy_files: string | null, parallel_setup_script: boolean | null, };

export type WorkspaceRepo = { id: string, workspace_id: string, repo_id: string, target_branch: string, created_at: Date, updated_at: Date, };

export type CreateWorkspaceRepo = { repo_id: string, target_branch: string, };

export type RepoWithTargetBranch = { target_branch: string, id: string, path: string, name: string, display_name: string, created_at: Date, updated_at: Date, };

export type Tag = { id: string, tag_name: string, content: string, created_at: string, updated_at: string, };

export type CreateTag = { tag_name: string, content: string, };

export type UpdateTag = { tag_name: string | null, content: string | null, };

export type TaskStatus = "todo" | "inprogress" | "inreview" | "done" | "cancelled";

export type TaskState = "queued" | "transitioning";

export type AgentStatus = "running" | "awaitingresponse";

export type Task = { id: string, project_id: string, title: string, description: string | null, status: TaskStatus, column_id: string | null, parent_workspace_id: string | null, shared_task_id: string | null, task_state: TaskState, agent_status: AgentStatus | null, created_at: string, updated_at: string, };

export type TaskWithAttemptStatus = { has_in_progress_attempt: boolean, last_attempt_failed: boolean, executor: string, latest_attempt_id: string | null, id: string, project_id: string, title: string, description: string | null, status: TaskStatus, column_id: string | null, parent_workspace_id: string | null, shared_task_id: string | null, task_state: TaskState, agent_status: AgentStatus | null, created_at: string, updated_at: string, };

export type TaskRelationships = { parent_task: Task | null, current_workspace: Workspace, children: Array<Task>, };

export type CreateTask = { project_id: string, title: string, description: string | null, status: TaskStatus | null, column_id: string | null, parent_workspace_id: string | null, image_ids: Array<string> | null, shared_task_id: string | null, };

export type UpdateTask = { title: string | null, description: string | null, status: TaskStatus | null, column_id: string | null, parent_workspace_id: string | null, image_ids: Array<string> | null, };

export type TaskTrigger = { id: string, 
/**
 * The task that will auto-start
 */
task_id: string, 
/**
 * The task to watch for completion
 */
trigger_task_id: string, 
/**
 * Condition for when to trigger (stored as string)
 */
trigger_on: string, 
/**
 * If true, trigger persists after firing; if false, removed after firing
 */
is_persistent: boolean, created_at: Date, 
/**
 * When this trigger was satisfied (null if not yet fired)
 */
fired_at: Date | null, };

export type CreateTaskTrigger = { task_id: string, trigger_task_id: string, trigger_on: string, is_persistent: boolean, };

export type TriggerCondition = "completed" | { "completed_with_status": string } | "merged";

export type TaskDependency = { id: string, 
/**
 * The blocked task
 */
task_id: string, 
/**
 * The prerequisite task that must complete first
 */
depends_on_task_id: string, created_at: Date, 
/**
 * When this dependency was satisfied (null if still blocking)
 */
satisfied_at: Date | null, };

export type CreateTaskDependency = { task_id: string, depends_on_task_id: string, };

export type TaskLabel = { id: string, project_id: string, name: string, color: string | null, position: number, created_at: Date, };

export type CreateTaskLabel = { 
/**
 * Project ID - can be omitted from JSON body if provided via URL path
 */
project_id: string, name: string, color: string | null, position: number | null, };

export type UpdateTaskLabel = { name: string | null, color: string | null, position: number | null, };

export type TaskLabelAssignment = { task_id: string, label_id: string, created_at: Date, };

export type DraftFollowUpData = { message: string, variant: string | null, };

export type ScratchPayload = { "type": "DRAFT_TASK", "data": string } | { "type": "DRAFT_FOLLOW_UP", "data": DraftFollowUpData };

export enum ScratchType { DRAFT_TASK = "DRAFT_TASK", DRAFT_FOLLOW_UP = "DRAFT_FOLLOW_UP" }

export type Scratch = { id: string, payload: ScratchPayload, created_at: string, updated_at: string, };

export type CreateScratch = { payload: ScratchPayload, };

export type UpdateScratch = { payload: ScratchPayload, };

export type Image = { id: string, file_path: string, original_name: string, mime_type: string | null, size_bytes: number, hash: string, created_at: string, updated_at: string, };

export type CreateImage = { file_path: string, original_name: string, mime_type: string | null, size_bytes: number, hash: string, };

export type Workspace = { id: string, task_id: string, container_ref: string | null, branch: string, agent_working_dir: string | null, setup_completed_at: string | null, 
/**
 * When set, this attempt has been cancelled (but history is preserved)
 */
cancelled_at: Date | null, 
/**
 * Final context captured before worktree deletion - what the agent learned/decided
 */
final_context: string | null, 
/**
 * Brief summary of what was accomplished in this attempt
 */
completion_summary: string | null, created_at: string, updated_at: string, };

export type Session = { id: string, workspace_id: string, executor: string | null, created_at: string, updated_at: string, };

export type ExecutionProcess = { id: string, session_id: string, run_reason: ExecutionProcessRunReason, executor_action: ExecutorAction, status: ExecutionProcessStatus, exit_code: number | null, 
/**
 * dropped: true if this process is excluded from the current
 * history view (due to restore/trimming). Hidden from logs/timeline;
 * still listed in the Processes tab.
 */
dropped: boolean, started_at: string, completed_at: string | null, created_at: string, updated_at: string, };

export enum ExecutionProcessStatus { running = "running", completed = "completed", failed = "failed", killed = "killed" }

export type ExecutionProcessRunReason = "setupscript" | "cleanupscript" | "codingagent" | "devserver";

export type ExecutionProcessRepoState = { id: string, execution_process_id: string, repo_id: string, before_head_commit: string | null, after_head_commit: string | null, merge_commit: string | null, created_at: Date, updated_at: Date, };

export type Merge = { "type": "direct" } & DirectMerge | { "type": "pr" } & PrMerge;

export type DirectMerge = { id: string, workspace_id: string, repo_id: string, merge_commit: string, target_branch_name: string, created_at: string, };

export type PrMerge = { id: string, workspace_id: string, repo_id: string, created_at: string, target_branch_name: string, pr_info: PullRequestInfo, };

export type MergeStatus = "open" | "merged" | "closed" | "unknown";

export type PullRequestInfo = { number: number, url: string, status: MergeStatus, merged_at: string | null, merge_commit_sha: string | null, };

export type ApprovalStatus = { "status": "pending" } | { "status": "approved" } | { "status": "denied", reason?: string, } | { "status": "timed_out" };

export type CreateApprovalRequest = { tool_name: string, tool_input: JsonValue, tool_call_id: string, };

export type ApprovalResponse = { execution_process_id: string, status: ApprovalStatus, };

export type Diff = { change: DiffChangeKind, oldPath: string | null, newPath: string | null, oldContent: string | null, newContent: string | null, 
/**
 * True when file contents are intentionally omitted (e.g., too large)
 */
contentOmitted: boolean, 
/**
 * Optional precomputed stats for omitted content
 */
additions: number | null, deletions: number | null, };

export type DiffChangeKind = "added" | "deleted" | "modified" | "renamed" | "copied" | "permissionChange";

export type ApiResponse<T, E = T> = { success: boolean, data: T | null, error_data: E | null, message: string | null, };

export type LoginStatus = { "status": "loggedout" } | { "status": "loggedin", profile: ProfileResponse, };

export type ProfileResponse = { user_id: string, username: string | null, email: string, providers: Array<ProviderProfile>, };

export type ProviderProfile = { provider: string, username: string | null, display_name: string | null, email: string | null, avatar_url: string | null, };

export type StatusResponse = { logged_in: boolean, profile: ProfileResponse | null, degraded: boolean | null, };

export enum MemberRole { ADMIN = "ADMIN", MEMBER = "MEMBER" }

export enum InvitationStatus { PENDING = "PENDING", ACCEPTED = "ACCEPTED", DECLINED = "DECLINED", EXPIRED = "EXPIRED" }

export type Organization = { id: string, name: string, slug: string, is_personal: boolean, created_at: string, updated_at: string, };

export type OrganizationWithRole = { id: string, name: string, slug: string, is_personal: boolean, created_at: string, updated_at: string, user_role: MemberRole, };

export type ListOrganizationsResponse = { organizations: Array<OrganizationWithRole>, };

export type GetOrganizationResponse = { organization: Organization, user_role: string, };

export type CreateOrganizationRequest = { name: string, slug: string, };

export type CreateOrganizationResponse = { organization: OrganizationWithRole, };

export type UpdateOrganizationRequest = { name: string, };

export type Invitation = { id: string, organization_id: string, invited_by_user_id: string | null, email: string, role: MemberRole, status: InvitationStatus, token: string, created_at: string, expires_at: string, };

export type CreateInvitationRequest = { email: string, role: MemberRole, };

export type CreateInvitationResponse = { invitation: Invitation, };

export type ListInvitationsResponse = { invitations: Array<Invitation>, };

export type GetInvitationResponse = { id: string, organization_slug: string, role: MemberRole, expires_at: string, };

export type AcceptInvitationResponse = { organization_id: string, organization_slug: string, role: MemberRole, };

export type RevokeInvitationRequest = { invitation_id: string, };

export type OrganizationMember = { user_id: string, role: MemberRole, joined_at: string, };

export type OrganizationMemberWithProfile = { user_id: string, role: MemberRole, joined_at: string, first_name: string | null, last_name: string | null, username: string | null, email: string | null, avatar_url: string | null, };

export type ListMembersResponse = { members: Array<OrganizationMemberWithProfile>, };

export type UpdateMemberRoleRequest = { role: MemberRole, };

export type UpdateMemberRoleResponse = { user_id: string, role: MemberRole, };

export type RemoteProject = { id: string, organization_id: string, name: string, metadata: Record<string, unknown>, created_at: string, };

export type ListProjectsResponse = { projects: Array<RemoteProject>, };

export type RemoteProjectMembersResponse = { organization_id: string, members: Array<OrganizationMemberWithProfile>, };

export type CreateRemoteProjectRequest = { organization_id: string, name: string, };

export type LinkToExistingRequest = { remote_project_id: string, };

export type RegisterRepoRequest = { path: string, display_name: string | null, };

export type InitRepoRequest = { parent_path: string, folder_name: string, };

export type TagSearchParams = { search: string | null, };

export type TokenResponse = { access_token: string, expires_at: string | null, };

export type UserSystemInfo = { config: Config, analytics_user_id: string, login_status: LoginStatus, environment: Environment, 
/**
 * Capabilities supported per executor (e.g., { "CLAUDE_CODE": ["SESSION_FORK"] })
 */
capabilities: { [key in string]?: Array<BaseAgentCapability> }, executors: { [key in BaseCodingAgent]?: ExecutorConfig }, };

export type Environment = { os_type: string, os_version: string, os_architecture: string, bitness: string, };

export type McpServerQuery = { executor: BaseCodingAgent, };

export type UpdateMcpServersBody = { servers: { [key in string]?: JsonValue }, };

export type GetMcpServerResponse = { mcp_config: McpConfig, config_path: string, };

export type CheckEditorAvailabilityQuery = { editor_type: EditorType, };

export type CheckEditorAvailabilityResponse = { available: boolean, };

export type CheckAgentAvailabilityQuery = { executor: BaseCodingAgent, };

export type CurrentUserResponse = { user_id: string, };

export type CreateFollowUpAttempt = { prompt: string, variant: string | null, retry_process_id: string | null, force_when_dirty: boolean | null, perform_git_reset: boolean | null, };

export type ChangeTargetBranchRequest = { repo_id: string, new_target_branch: string, };

export type ChangeTargetBranchResponse = { repo_id: string, new_target_branch: string, status: [number, number], };

export type MergeTaskAttemptRequest = { repo_id: string, };

export type PushTaskAttemptRequest = { repo_id: string, };

export type RenameBranchRequest = { new_branch_name: string, };

export type RenameBranchResponse = { branch: string, };

export type OpenEditorRequest = { editor_type: string | null, file_path: string | null, };

export type OpenEditorResponse = { url: string | null, };

export type AssignSharedTaskRequest = { new_assignee_user_id: string | null, };

export type ShareTaskResponse = { shared_task_id: string, };

export type CreateAndStartTaskRequest = { task: CreateTask, executor_profile_id: ExecutorProfileId, repos: Array<WorkspaceRepoInput>, };

export type CreateGitHubPrRequest = { title: string, body: string | null, target_branch: string | null, draft: boolean | null, repo_id: string, auto_generate_description: boolean, };

export type ImageResponse = { id: string, file_path: string, original_name: string, mime_type: string | null, size_bytes: bigint, hash: string, created_at: string, updated_at: string, };

export type ImageMetadata = { exists: boolean, file_name: string | null, path: string | null, size_bytes: bigint | null, format: string | null, proxy_url: string | null, };

export type ApplyTemplateRequest = { template_board_id: string, };

export type ApplyTemplateResponse = { board_id: string, agents_created: number, columns_created: number, transitions_created: number, };

export type SaveAsTemplateRequest = { template_name: string, template_description: string, template_icon: string, };

export type SaveAsTemplateResponse = { template_board_id: string, template_group_id: string, agents_cloned: number, columns_cloned: number, transitions_cloned: number, };

export type CreateTaskAttemptBody = { task_id: string, executor_profile_id: ExecutorProfileId, repos: Array<WorkspaceRepoInput>, };

export type WorkspaceRepoInput = { repo_id: string, target_branch: string, };

export type RunAgentSetupRequest = { executor_profile_id: ExecutorProfileId, };

export type RunAgentSetupResponse = Record<string, never>;

export type GhCliSetupError = "BREW_MISSING" | "SETUP_HELPER_NOT_SUPPORTED" | { "OTHER": { message: string, } };

export type RebaseTaskAttemptRequest = { repo_id: string, old_base_branch: string | null, new_base_branch: string | null, };

export type AbortConflictsRequest = { repo_id: string, };

export type GitOperationError = { "type": "merge_conflicts", message: string, op: ConflictOp, } | { "type": "rebase_in_progress" };

export type PushError = { "type": "force_push_required" };

export type CreatePrError = { "type": "github_cli_not_installed" } | { "type": "github_cli_not_logged_in" } | { "type": "git_cli_not_logged_in" } | { "type": "git_cli_not_installed" } | { "type": "target_branch_not_found", branch: string, };

export type BranchStatus = { commits_behind: number | null, commits_ahead: number | null, has_uncommitted_changes: boolean | null, head_oid: string | null, uncommitted_count: number | null, untracked_count: number | null, target_branch_name: string, remote_commits_behind: number | null, remote_commits_ahead: number | null, merges: Array<Merge>, 
/**
 * True if a `git rebase` is currently in progress in this worktree
 */
is_rebase_in_progress: boolean, 
/**
 * Current conflict operation if any
 */
conflict_op: ConflictOp | null, 
/**
 * List of files currently in conflicted (unmerged) state
 */
conflicted_files: Array<string>, };

export type RunScriptError = { "type": "no_script_configured" } | { "type": "process_already_running" };

export type AttachPrResponse = { pr_attached: boolean, pr_url: string | null, pr_number: bigint | null, pr_status: MergeStatus | null, };

export type AttachExistingPrRequest = { repo_id: string, };

export type PrCommentsResponse = { comments: Array<UnifiedPrComment>, };

export type GetPrCommentsError = { "type": "no_pr_attached" } | { "type": "github_cli_not_installed" } | { "type": "github_cli_not_logged_in" };

export type GetPrCommentsQuery = { repo_id: string, };

export type UnifiedPrComment = { "comment_type": "general", id: string, author: string, author_association: string, body: string, created_at: string, url: string, } | { "comment_type": "review", id: bigint, author: string, author_association: string, body: string, created_at: string, url: string, path: string, line: bigint | null, diff_hunk: string, };

export type RepoBranchStatus = { repo_id: string, repo_name: string, commits_behind: number | null, commits_ahead: number | null, has_uncommitted_changes: boolean | null, head_oid: string | null, uncommitted_count: number | null, untracked_count: number | null, target_branch_name: string, remote_commits_behind: number | null, remote_commits_ahead: number | null, merges: Array<Merge>, 
/**
 * True if a `git rebase` is currently in progress in this worktree
 */
is_rebase_in_progress: boolean, 
/**
 * Current conflict operation if any
 */
conflict_op: ConflictOp | null, 
/**
 * List of files currently in conflicted (unmerged) state
 */
conflicted_files: Array<string>, };

export type DirectoryEntry = { name: string, path: string, is_directory: boolean, is_git_repo: boolean, last_modified: bigint | null, };

export type DirectoryListResponse = { entries: Array<DirectoryEntry>, current_path: string, };

export type Config = { config_version: string, theme: ThemeMode, executor_profile: ExecutorProfileId, disclaimer_acknowledged: boolean, onboarding_acknowledged: boolean, notifications: NotificationConfig, editor: EditorConfig, github: GitHubConfig, analytics_enabled: boolean, workspace_dir: string | null, last_app_version: string | null, show_release_notes: boolean, language: UiLanguage, git_branch_prefix: string, showcases: ShowcaseState, pr_auto_description_enabled: boolean, pr_auto_description_prompt: string | null, };

export type NotificationConfig = { sound_enabled: boolean, push_enabled: boolean, sound_file: SoundFile, };

export enum ThemeMode { LIGHT = "LIGHT", DARK = "DARK", SYSTEM = "SYSTEM" }

export type EditorConfig = { editor_type: EditorType, custom_command: string | null, remote_ssh_host: string | null, remote_ssh_user: string | null, };

export enum EditorType { VS_CODE = "VS_CODE", CURSOR = "CURSOR", WINDSURF = "WINDSURF", INTELLI_J = "INTELLI_J", ZED = "ZED", XCODE = "XCODE", CUSTOM = "CUSTOM" }

export type EditorOpenError = { "type": "executable_not_found", executable: string, editor_type: EditorType, } | { "type": "invalid_command", details: string, editor_type: EditorType, } | { "type": "launch_failed", executable: string, details: string, editor_type: EditorType, };

export type GitHubConfig = { pat: string | null, oauth_token: string | null, username: string | null, primary_email: string | null, default_pr_base: string | null, };

export enum SoundFile { ABSTRACT_SOUND1 = "ABSTRACT_SOUND1", ABSTRACT_SOUND2 = "ABSTRACT_SOUND2", ABSTRACT_SOUND3 = "ABSTRACT_SOUND3", ABSTRACT_SOUND4 = "ABSTRACT_SOUND4", COW_MOOING = "COW_MOOING", PHONE_VIBRATION = "PHONE_VIBRATION", ROOSTER = "ROOSTER" }

export type UiLanguage = "BROWSER" | "EN" | "JA" | "ES" | "KO" | "ZH_HANS";

export type ShowcaseState = { seen_features: Array<string>, };

export type GitBranch = { name: string, is_current: boolean, is_remote: boolean, last_commit_date: Date, };

export type SharedTaskDetails = { id: string, project_id: string, title: string, description: string | null, status: TaskStatus, };

export type RemoteTaskStatus = "todo" | "inprogress" | "inreview" | "done" | "cancelled";

export type SharedTaskResponse = { task: SharedTask, };

export type SharedTaskData = { id: string, project_id: string, title: string, description: string | null, status: RemoteTaskStatus, assignee_user_id: string | null, creator_user_id: string | null, };

export type SharedTask = { id: string, organization_id: string, project_id: string, creator_user_id: string | null, assignee_user_id: string | null, deleted_by_user_id: string | null, title: string, description: string | null, status: RemoteTaskStatus, deleted_at: Date | null, shared_at: Date | null, created_at: Date, updated_at: Date, };

export type UserData = { user_id: string, email: string | null, first_name: string | null, last_name: string | null, username: string | null, avatar_url: string | null, };

export type AssigneesQuery = { project_id: string, };

export type QueuedMessage = { 
/**
 * The session this message is queued for
 */
session_id: string, 
/**
 * The follow-up data (message + variant)
 */
data: DraftFollowUpData, 
/**
 * Timestamp when the message was queued
 */
queued_at: string, };

export type QueueStatus = { "status": "empty" } | { "status": "queued", message: QueuedMessage, };

export type ConflictOp = "rebase" | "merge" | "cherry_pick" | "revert";

export type ExecutorAction = { typ: ExecutorActionType, next_action: ExecutorAction | null, };

export type McpConfig = { servers: { [key in string]?: JsonValue }, servers_path: Array<string>, template: JsonValue, preconfigured: JsonValue, is_toml_config: boolean, };

export type ExecutorActionType = { "type": "CodingAgentInitialRequest" } & CodingAgentInitialRequest | { "type": "CodingAgentFollowUpRequest" } & CodingAgentFollowUpRequest | { "type": "ScriptRequest" } & ScriptRequest;

export type ScriptContext = "SetupScript" | "CleanupScript" | "DevServer" | "ToolInstallScript";

export type ScriptRequest = { script: string, language: ScriptRequestLanguage, context: ScriptContext, 
/**
 * Optional relative path to execute the script in (relative to container_ref).
 * If None, uses the container_ref directory directly.
 */
working_dir: string | null, };

export type ScriptRequestLanguage = "Bash";

export enum BaseCodingAgent { CLAUDE_CODE = "CLAUDE_CODE", AMP = "AMP", GEMINI = "GEMINI", CODEX = "CODEX", OPENCODE = "OPENCODE", CURSOR_AGENT = "CURSOR_AGENT", QWEN_CODE = "QWEN_CODE", COPILOT = "COPILOT", DROID = "DROID" }

export type CodingAgent = { "CLAUDE_CODE": ClaudeCode } | { "AMP": Amp } | { "GEMINI": Gemini } | { "CODEX": Codex } | { "OPENCODE": Opencode } | { "CURSOR_AGENT": CursorAgent } | { "QWEN_CODE": QwenCode } | { "COPILOT": Copilot } | { "DROID": Droid };

export type AvailabilityInfo = { "type": "LOGIN_DETECTED", last_auth_timestamp: bigint, } | { "type": "INSTALLATION_FOUND" } | { "type": "NOT_FOUND" };

export type CommandBuilder = { 
/**
 * Base executable command (e.g., "npx -y @anthropic-ai/claude-code@latest")
 */
base: string, 
/**
 * Optional parameters to append to the base command
 */
params: Array<string> | null, };

export type ExecutorProfileId = { 
/**
 * The executor type (e.g., "CLAUDE_CODE", "AMP")
 */
executor: BaseCodingAgent, 
/**
 * Optional variant name (e.g., "PLAN", "ROUTER")
 */
variant: string | null, };

export type ExecutorConfig = { [key in string]?: { "CLAUDE_CODE": ClaudeCode } | { "AMP": Amp } | { "GEMINI": Gemini } | { "CODEX": Codex } | { "OPENCODE": Opencode } | { "CURSOR_AGENT": CursorAgent } | { "QWEN_CODE": QwenCode } | { "COPILOT": Copilot } | { "DROID": Droid } };

export type ExecutorConfigs = { executors: { [key in BaseCodingAgent]?: ExecutorConfig }, };

export enum BaseAgentCapability { SESSION_FORK = "SESSION_FORK", SETUP_HELPER = "SETUP_HELPER" }

export type ClaudeCode = { append_prompt: AppendPrompt, claude_code_router?: boolean | null, plan?: boolean | null, approvals?: boolean | null, model?: string | null, dangerously_skip_permissions?: boolean | null, disable_api_key?: boolean | null, base_command_override?: string | null, additional_params?: Array<string> | null, env?: { [key in string]?: string } | null, };

export type Gemini = { append_prompt: AppendPrompt, model?: string | null, yolo?: boolean | null, base_command_override?: string | null, additional_params?: Array<string> | null, env?: { [key in string]?: string } | null, };

export type Amp = { append_prompt: AppendPrompt, dangerously_allow_all?: boolean | null, base_command_override?: string | null, additional_params?: Array<string> | null, env?: { [key in string]?: string } | null, };

export type Codex = { append_prompt: AppendPrompt, sandbox?: SandboxMode | null, ask_for_approval?: AskForApproval | null, oss?: boolean | null, model?: string | null, model_reasoning_effort?: ReasoningEffort | null, model_reasoning_summary?: ReasoningSummary | null, model_reasoning_summary_format?: ReasoningSummaryFormat | null, profile?: string | null, base_instructions?: string | null, include_apply_patch_tool?: boolean | null, model_provider?: string | null, compact_prompt?: string | null, developer_instructions?: string | null, base_command_override?: string | null, additional_params?: Array<string> | null, env?: { [key in string]?: string } | null, };

export type SandboxMode = "auto" | "read-only" | "workspace-write" | "danger-full-access";

export type AskForApproval = "unless-trusted" | "on-failure" | "on-request" | "never";

export type ReasoningEffort = "low" | "medium" | "high" | "xhigh";

export type ReasoningSummary = "auto" | "concise" | "detailed" | "none";

export type ReasoningSummaryFormat = "none" | "experimental";

export type CursorAgent = { append_prompt: AppendPrompt, force?: boolean | null, model?: string | null, base_command_override?: string | null, additional_params?: Array<string> | null, env?: { [key in string]?: string } | null, };

export type Copilot = { append_prompt: AppendPrompt, model?: string | null, allow_all_tools?: boolean | null, allow_tool?: string | null, deny_tool?: string | null, add_dir?: Array<string> | null, disable_mcp_server?: Array<string> | null, base_command_override?: string | null, additional_params?: Array<string> | null, env?: { [key in string]?: string } | null, };

export type Opencode = { append_prompt: AppendPrompt, model?: string | null, mode?: string | null, 
/**
 * Auto-approve agent actions
 */
auto_approve: boolean, base_command_override?: string | null, additional_params?: Array<string> | null, env?: { [key in string]?: string } | null, };

export type QwenCode = { append_prompt: AppendPrompt, yolo?: boolean | null, base_command_override?: string | null, additional_params?: Array<string> | null, env?: { [key in string]?: string } | null, };

export type Droid = { append_prompt: AppendPrompt, autonomy: Autonomy, model?: string | null, reasoning_effort?: DroidReasoningEffort | null, base_command_override?: string | null, additional_params?: Array<string> | null, env?: { [key in string]?: string } | null, };

export type Autonomy = "normal" | "low" | "medium" | "high" | "skip-permissions-unsafe";

export type DroidReasoningEffort = "none" | "dynamic" | "off" | "low" | "medium" | "high";

export type AppendPrompt = string | null;

export type CodingAgentInitialRequest = { prompt: string, 
/**
 * Executor profile specification
 */
executor_profile_id: ExecutorProfileId, 
/**
 * Optional relative path to execute the agent in (relative to container_ref).
 * If None, uses the container_ref directory directly.
 */
working_dir: string | null, 
/**
 * Optional agent system prompt to prepend (establishes persona/role)
 */
agent_system_prompt: string | null, 
/**
 * Optional project context from context artifacts (ADRs, patterns, module memories)
 */
agent_project_context: string | null, 
/**
 * Optional workflow history showing prior work from other columns
 */
agent_workflow_history: string | null, 
/**
 * Optional agent start command to append (initial instruction)
 */
agent_start_command: string | null, 
/**
 * Optional deliverable description - tells the agent what to produce and when to stop
 */
agent_deliverable: string | null, };

export type CodingAgentFollowUpRequest = { prompt: string, session_id: string, 
/**
 * Executor profile specification
 */
executor_profile_id: ExecutorProfileId, 
/**
 * Optional relative path to execute the agent in (relative to container_ref).
 * If None, uses the container_ref directory directly.
 */
working_dir: string | null, };

export type CommandExitStatus = { "type": "exit_code", code: number, } | { "type": "success", success: boolean, };

export type CommandRunResult = { exit_status: CommandExitStatus | null, output: string | null, };

export type NormalizedEntry = { timestamp: string | null, entry_type: NormalizedEntryType, content: string, 
/**
 * Agent ID if this entry was produced during agent-context execution
 */
agent_id?: string | null, 
/**
 * Agent color (hex) for UI styling
 */
agent_color?: string | null, };

export type NormalizedEntryType = { "type": "user_message" } | { "type": "user_feedback", denied_tool: string, } | { "type": "assistant_message" } | { "type": "tool_use", tool_name: string, action_type: ActionType, status: ToolStatus, } | { "type": "system_message" } | { "type": "agent_switch", agent_name: string, agent_color: string | null, column_name: string, } | { "type": "error_message", error_type: NormalizedEntryError, } | { "type": "thinking" } | { "type": "loading" } | { "type": "next_action", failed: boolean, execution_processes: number, needs_setup: boolean, };

export type FileChange = { "action": "write", content: string, } | { "action": "delete" } | { "action": "rename", new_path: string, } | { "action": "edit", 
/**
 * Unified diff containing file header and hunks.
 */
unified_diff: string, 
/**
 * Whether line number in the hunks are reliable.
 */
has_line_numbers: boolean, };

export type ActionType = { "action": "file_read", path: string, } | { "action": "file_edit", path: string, changes: Array<FileChange>, } | { "action": "command_run", command: string, result: CommandRunResult | null, } | { "action": "search", query: string, } | { "action": "web_fetch", url: string, } | { "action": "tool", tool_name: string, arguments: JsonValue | null, result: ToolResult | null, } | { "action": "task_create", description: string, } | { "action": "plan_presentation", plan: string, } | { "action": "todo_management", todos: Array<TodoItem>, operation: string, } | { "action": "other", description: string, };

export type TodoItem = { content: string, status: string, priority: string | null, };

export type NormalizedEntryError = { "type": "setup_required" } | { "type": "other" };

export type ToolResult = { type: ToolResultValueType, 
/**
 * For Markdown, this will be a JSON string; for JSON, a structured value
 */
value: JsonValue, };

export type ToolResultValueType = { "type": "markdown" } | { "type": "json" };

export type ToolStatus = { "status": "created" } | { "status": "success" } | { "status": "failed" } | { "status": "denied", reason: string | null, } | { "status": "pending_approval", approval_id: string, requested_at: string, timeout_at: string, } | { "status": "timed_out" };

export type PatchType = { "type": "NORMALIZED_ENTRY", "content": NormalizedEntry } | { "type": "STDOUT", "content": string } | { "type": "STDERR", "content": string } | { "type": "DIFF", "content": Diff };

export type JsonValue = number | string | boolean | Array<JsonValue> | { [key in string]?: JsonValue } | null;

export type Agent = { id: string, name: string, role: string, system_prompt: string, capabilities: string | null, tools: string | null, description: string | null, context_files: string | null, executor: string, color: string | null, start_command: string | null, is_template: boolean, template_group_id: string | null, created_at: Date, updated_at: Date, };

export type CreateAgent = { name: string, role: string, system_prompt: string, capabilities: Array<string> | null, tools: Array<string> | null, description: string | null, context_files: Array<ContextFile> | null, executor: string | null, color: string | null, start_command: string | null, };

export type UpdateAgent = { name: string | null, role: string | null, system_prompt: string | null, capabilities: Array<string> | null, tools: Array<string> | null, description: string | null, context_files: Array<ContextFile> | null, executor: string | null, color: string | null, start_command: string | null, };

export type ContextFile = { pattern: string, instruction: string | null, };

export type AutomationRule = { id: string, project_id: string, column_id: string, trigger_type: string, action_type: string, action_config: string, enabled: boolean, priority: number, name: string | null, created_at: Date, updated_at: Date, };

export type AutomationRuleWithColumn = { id: string, project_id: string, column_id: string, column_name: string, trigger_type: string, action_type: string, action_config: string, enabled: boolean, priority: number, name: string | null, created_at: Date, updated_at: Date, };

export type CreateAutomationRule = { column_id: string, trigger_type: TriggerType, action_type: AutomationActionType, action_config: JsonValue, enabled: boolean | null, priority: number | null, name: string | null, };

export type UpdateAutomationRule = { trigger_type: TriggerType | null, action_type: AutomationActionType | null, action_config: JsonValue | null, enabled: boolean | null, priority: number | null, name: string | null, };

export type TriggerType = "on_enter" | "on_exit";

export type AutomationActionType = "run_agent" | "create_workspace" | "create_pr" | "merge_pr" | "webhook" | "notify";

export type RunAgentConfig = { agent_id: string | null, prompt_template: string, executor: string | null, timeout_minutes: number | null, };

export type CreateWorkspaceConfig = { 
/**
 * Executor to use (e.g., "local", "docker")
 */
executor: string | null, 
/**
 * Optional branch name template (uses default if not provided)
 */
branch_template: string | null, };

export type CreatePrConfig = { title_template: string, body_template: string, draft: boolean | null, auto_merge_on_approval: boolean | null, };

export type WebhookConfig = { url: string, method: string | null, headers: JsonValue | null, body_template: string | null, };

export type NotifyConfig = { channel: string, webhook_url: string, message_template: string, };

export type TaskEventType = "column_enter" | "column_exit" | "agent_start" | "agent_complete" | "agent_failed" | "commit" | "manual_action" | "task_created" | "status_change" | "else_transition" | "decision_validation_failed" | "artifact_created";

export type EventTriggerType = "manual" | "automation" | "drag_drop" | "system";

export type ActorType = "user" | "agent" | "system";

export type TaskEvent = { id: string, task_id: string, event_type: TaskEventType, from_column_id: string | null, to_column_id: string | null, workspace_id: string | null, session_id: string | null, executor: string | null, automation_rule_id: string | null, trigger_type: EventTriggerType | null, commit_hash: string | null, commit_message: string | null, metadata: JsonValue | null, actor_type: ActorType, actor_id: string | null, created_at: Date, };

export type TaskEventWithNames = { from_column_name: string | null, to_column_name: string | null, agent_name: string | null, agent_color: string | null, id: string, task_id: string, event_type: TaskEventType, from_column_id: string | null, to_column_id: string | null, workspace_id: string | null, session_id: string | null, executor: string | null, automation_rule_id: string | null, trigger_type: EventTriggerType | null, commit_hash: string | null, commit_message: string | null, metadata: JsonValue | null, actor_type: ActorType, actor_id: string | null, created_at: Date, };

export type CreateTaskEvent = { task_id: string, event_type: TaskEventType, from_column_id: string | null, to_column_id: string | null, workspace_id: string | null, session_id: string | null, executor: string | null, automation_rule_id: string | null, trigger_type: EventTriggerType | null, commit_hash: string | null, commit_message: string | null, metadata: JsonValue | null, actor_type: ActorType | null, actor_id: string | null, };

export type ArtifactType = "module_memory" | "adr" | "decision" | "pattern" | "dependency" | "iplan" | "changelog_entry";

export type ArtifactScope = "path" | "task" | "global";

export type ContextArtifact = { id: string, project_id: string, artifact_type: string, 
/**
 * File/module path this relates to (for module memories)
 */
path: string | null, title: string, content: string, metadata: string | null, source_task_id: string | null, source_commit_hash: string | null, 
/**
 * Scope determines when this artifact is included in context
 */
scope: string, 
/**
 * Relative file path on disk (e.g., 'docs/adr/0001-use-postgres.md')
 */
file_path: string | null, 
/**
 * ID of the artifact this one supersedes (for version tracking)
 */
supersedes_id: string | null, 
/**
 * Chain ID groups all versions of the same logical document
 */
chain_id: string | null, 
/**
 * Version number within a chain (1, 2, 3...)
 */
version: number, 
/**
 * Approximate token count for budget-aware context injection (content.len() / 4)
 */
token_estimate: number, created_at: Date, updated_at: Date, };

export type CreateContextArtifact = { project_id: string, artifact_type: ArtifactType, path: string | null, title: string, content: string, metadata: JsonValue | null, source_task_id: string | null, source_commit_hash: string | null, scope: ArtifactScope, 
/**
 * Relative file path on disk (e.g., 'docs/adr/0001-use-postgres.md')
 */
file_path: string | null, 
/**
 * ID of the artifact this one supersedes (for version tracking)
 */
supersedes_id: string | null, 
/**
 * Chain ID - if not provided, will be auto-generated for new chains
 */
chain_id: string | null, };

export type UpdateContextArtifact = { title: string | null, content: string | null, metadata: JsonValue | null, scope: ArtifactScope | null, };

export type ContextPreviewStats = { context: string, tokens_used: number, token_budget: number, artifacts_included: number, artifacts_total: number, };

export type EvaluateRun = { id: string, commit_hash: string | null, commit_message: string | null, project_name: string, started_at: string, completed_at: string, 
/**
 * JSON blob: { tasks, artifacts, events, context_previews }
 */
summary: EvaluateRunSummary, notes: string | null, created_at: string, };

export type EvaluateRunSummary = { tasks: Array<EvaluateRunTask>, artifacts: Array<EvaluateRunArtifact>, events: Array<EvaluateRunEvent>, stats: EvaluateRunStats, };

export type EvaluateRunTask = { title: string, status: string, agent_status: string | null, attempts: Array<EvaluateRunAttempt>, };

export type EvaluateRunAttempt = { branch: string, completion_summary: string | null, final_context: string | null, };

export type EvaluateRunArtifact = { artifact_type: string, scope: string, title: string, token_estimate: number, content: string, };

export type EvaluateRunEvent = { event_type: string, column_name: string | null, commit_message: string | null, created_at: string, };

export type EvaluateRunStats = { total_tasks: number, tasks_completed: number, total_artifacts: number, total_tokens: number, total_events: number, };

export type CreateEvaluateRun = { commit_hash: string | null, commit_message: string | null, project_name: string, started_at: string, summary: JsonValue, notes: string | null, };

export const DEFAULT_PR_DESCRIPTION_PROMPT = `Update the GitHub PR that was just created with a better title and description.
The PR number is #{pr_number} and the URL is {pr_url}.

Analyze the changes in this branch and write:
1. A concise, descriptive title that summarizes the changes, postfixed with "(Vibe Kanban)"
2. A detailed description that explains:
   - What changes were made
   - Why they were made (based on the task context)
   - Any important implementation details
   - At the end, include a note: "This PR was written using [Vibe Kanban](https://vibekanban.com)"

Use \`gh pr edit\` to update the PR.`;